### ISSUE TITLE
[Suggest a feature] provide some options

### ISSUE THREAD

**Issue by PENEKhun** [easypeel-security/easypeel-method-security#38]
ex)

```yml
easypeel-security:
  enable: true
  log:
    enable: true
```
